### ISSUE TITLE
NullReferenceException during build

### ISSUE THREAD

**Issue by MarkMuth** [affederaffe/Tmds.DBus.SourceGenerator#26] opened 2024-09-09 20:16 UTC
Creating a Proxy for NetworkManager does not work with the current versions of Tmds.DBus.Protocol and Tmds.DBus.SourceGenerator.

Here is what I did:

```
dotnet new console --name SourceGenerator
cd SourceGenerator
dotnet add package Tmds.DBus.SourceGenerator
dotnet add package Tmds.DBus.Protocol
busctl introspect org.freedesktop.NetworkManager /org/freedesktop/NetworkManager --xml-interface > NetworkManager.xml
```

The final `SourceGenerator.csproj` file is this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.20.0" />
    <PackageReference Include="Tmds.DBus.SourceGenerator" Version="0.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <AdditionalFiles Include="NetworkManager.xml" DBusGeneratorMode="Proxy" />
  </ItemGroup>

</Project>
```

Now after `dotnet build` I get the following output and no code is generated at all:

```
Build succeeded.

CSC : warning CS8785: Generator 'DBusSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/path/to/SourceGenerator/SourceGenerator.csproj]
    1 Warning(s)
    0 Error(s)
```

For now, my workaround is to downgrade to:

```
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.16.0" />
    <PackageReference Include="Tmds.DBus.SourceGenerator" Version="0.0.15">
```

**Comment by ash-microconnect** [comment] 2024-09-13 06:05
@MarkMuth: Thanks for posting your workaround, it helped me continue with my project. 

@affederaffe:
From the debug/analysis I performed, it seems the problem is triggered when trying to process a property with `write` or `readwrite` access, such as the `WirelessEnabled` property of `NetworkManager`. If I remove/delete all `write` or  `readwrite` properties from the XML, I don't get the error; similarly, if I change them to `read` I don't get the error.

The error message and stack trace of the exception is:

<pre>
    CSC : warning CS8785: Generator 'DBusSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.
    System.NullReferenceException: Object reference not set to an instance of an object.
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.SanitizeSignature(String signature)
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.GetOrAddWriteVariantMethod(DBusValue dBusValue)
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.MakeSetMethod(DBusProperty dBusProperty)
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.<AddProperties>b__46_0(ClassDeclarationSyntax current, DBusProperty dBusProperty)
    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.AddProperties(ClassDeclarationSyntax& cl, DBusInterface dBusInterface)
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.GenerateProxy(DBusInterface dBusInterface)
    at Tmds.DBus.SourceGenerator.DBusSourceGenerator.<>c__DisplayClass8_0.<Initialize>b__4(SourceProductionContext productionContext, ImmutableArray`1 provider)
    at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0`2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)
</pre>

Attached is XML file for NetworkManager: [org.freedesktop.NetworkManager.xml.zip](https://github.com/user-attachments/files/16989260/org.freedesktop.NetworkManager.xml.zip)

**Comment by affederaffe** [comment] 2024-09-13 20:23
Thanks for your report, this should be fixed with https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/3000d910f9275aa900468458b9562d196ae2c0e1.

**Closed as completed** 2024-09-17 14:43 UTC
