### ISSUE TITLE
fails to parse type="h"

### ISSUE THREAD

**Issue by 17steen** [affederaffe/Tmds.DBus.SourceGenerator#14] opened 2024-05-21 13:24 UTC
This xml cannot get parsed: https://raw.githubusercontent.com/flatpak/xdg-desktop-portal/main/data/org.freedesktop.portal.ScreenCast.xml

I believe it fails at parsing this: 
```xml
      <arg type="h" name="fd" direction="out"/>
```

Maybe this library doesn't support the "h" type?

**Comment by ShortDevelopment** [comment] 2024-06-07 13:46
Oh, did I generate a duplicate of this? 😅
See #15

**Closed as completed** 2024-06-08 09:09 UTC
